export enum AuditAction {
  // Auth events
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  
  // User management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  
  // Data events
  CONTACT_CREATED = 'CONTACT_CREATED',
  CONTACT_UPDATED = 'CONTACT_UPDATED',
  CONTACT_DELETED = 'CONTACT_DELETED',
  DEAL_CREATED = 'DEAL_CREATED',
  DEAL_UPDATED = 'DEAL_UPDATED',
  DEAL_DELETED = 'DEAL_DELETED',
  PIPELINE_CREATED = 'PIPELINE_CREATED',
  PIPELINE_UPDATED = 'PIPELINE_UPDATED',
  PIPELINE_DELETED = 'PIPELINE_DELETED',
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  LEAD_DELETED = 'LEAD_DELETED',
  
  // System events
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  CSRF_FAILURE = 'CSRF_FAILURE',
  RATE_LIMIT_TRIGGERED = 'RATE_LIMIT_TRIGGERED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}