export const AuditAction = {
  // Auth events
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  TOKEN_REFRESH: 'TOKEN_REFRESH',

  // User management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',

  // Data events
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  DEAL_CREATED: 'DEAL_CREATED',
  DEAL_UPDATED: 'DEAL_UPDATED',
  DEAL_DELETED: 'DEAL_DELETED',
  PIPELINE_CREATED: 'PIPELINE_CREATED',
  PIPELINE_UPDATED: 'PIPELINE_UPDATED',
  PIPELINE_DELETED: 'PIPELINE_DELETED',
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_DELETED: 'LEAD_DELETED',

  // System events
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  CSRF_FAILURE: 'CSRF_FAILURE',
  RATE_LIMIT_TRIGGERED: 'RATE_LIMIT_TRIGGERED',
  SYSTEM_ERROR: 'SYSTEM_ERROR',

  // Extended actions
  ANALYTICS_EXPORT_REQUESTED: 'ANALYTICS_EXPORT_REQUESTED',
  ANALYTICS_EXPORT_DOWNLOADED: 'ANALYTICS_EXPORT_DOWNLOADED',
  ANALYTICS_EXPORT_COMPLETED: 'ANALYTICS_EXPORT_COMPLETED',
  ANALYTICS_EXPORT_FAILED: 'ANALYTICS_EXPORT_FAILED',

  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',

  // Webhook events
  WEBHOOK_CREATED: 'WEBHOOK_CREATED',
  WEBHOOK_UPDATED: 'WEBHOOK_UPDATED',
  WEBHOOK_DELETED: 'WEBHOOK_DELETED',
  WEBHOOK_TRIGGERED: 'WEBHOOK_TRIGGERED',
  WEBHOOK_RETRY: 'WEBHOOK_RETRY',
  WEBHOOK_CLEANUP: 'WEBHOOK_CLEANUP',
  WEBHOOK_DELIVERED: 'WEBHOOK_DELIVERED',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
} as const;

export const AuditEntityType = {
  AUTH: 'AUTH',
  USER: 'USER',
  CONTACT: 'CONTACT',
  DEAL: 'DEAL',
  PIPELINE: 'PIPELINE',
  LEAD: 'LEAD',
  ACCOUNT: 'ACCOUNT',
  ACTIVITY: 'ACTIVITY',
  SYSTEM: 'SYSTEM',
  WEBHOOK: 'WEBHOOK',
  WEBHOOK_DELIVERY: 'WEBHOOK_DELIVERY',
} as const;

export const AuditSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
export type AuditEntityTypeType =
  (typeof AuditEntityType)[keyof typeof AuditEntityType];
export type AuditSeverityType =
  (typeof AuditSeverity)[keyof typeof AuditSeverity];
