/**
 * Centralized error codes for the HelixCRM API
 * 
 * Error codes follow the pattern: MODULE_ERROR_TYPE
 * Where:
 * - MODULE: auth, tenant, validation, rate, system
 * - ERROR: descriptive error type
 * - TYPE: optional subtype
 */
export enum ErrorCode {
  // ==================== AUTHENTICATION ERRORS ====================
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_REFRESH_TOKEN_REVOKED = 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_MUST_CHANGE_PASSWORD = 'AUTH_MUST_CHANGE_PASSWORD',
  AUTH_PASSWORD_RESET_REQUIRED = 'AUTH_PASSWORD_RESET_REQUIRED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_CSRF_TOKEN_MISSING = 'AUTH_CSRF_TOKEN_MISSING',
  AUTH_CSRF_TOKEN_INVALID = 'AUTH_CSRF_TOKEN_INVALID',

  // ==================== TENANT & ORGANIZATION ERRORS ====================
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ACCESS_DENIED = 'ORGANIZATION_ACCESS_DENIED',

  // ==================== VALIDATION & DATA ERRORS ====================
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE',

  // ==================== RATE LIMITING ERRORS ====================
  RATE_LIMITED = 'RATE_LIMITED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // ==================== PERMISSION & RBAC ERRORS ====================
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  INSUFFICIENT_PRIVILEGES = 'INSUFFICIENT_PRIVILEGES',
  FORBIDDEN_OPERATION = 'FORBIDDEN_OPERATION',

  // ==================== DATABASE & RLS ERRORS ====================
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  RLS_POLICY_VIOLATION = 'RLS_POLICY_VIOLATION',
  RLS_CONTEXT_MISSING = 'RLS_CONTEXT_MISSING',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  CONSTRAINT_VIOLATION = 'CONSTRAINT_VIOLATION',
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',

  // ==================== EXTERNAL SERVICE ERRORS ====================
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EMAIL_SERVICE_FAILED = 'EMAIL_SERVICE_FAILED',
  STORAGE_SERVICE_FAILED = 'STORAGE_SERVICE_FAILED',
  PAYMENT_SERVICE_FAILED = 'PAYMENT_SERVICE_FAILED',
  THIRD_PARTY_API_ERROR = 'THIRD_PARTY_API_ERROR',

  // ==================== SYSTEM & INFRASTRUCTURE ERRORS ====================
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  VERSION_DEPRECATED = 'VERSION_DEPRECATED',
  UPGRADE_REQUIRED = 'UPGRADE_REQUIRED',
}

/**
 * Error categories for grouping and reporting
 */
export enum ErrorCategory {
  AUTHENTICATION = 'authentication',
  AUTHORIZATION = 'authorization',
  VALIDATION = 'validation',
  RATE_LIMITING = 'rate_limiting',
  DATABASE = 'database',
  EXTERNAL_SERVICE = 'external_service',
  SYSTEM = 'system',
  CLIENT = 'client',
}

/**
 * Error severity levels
 */
export enum ErrorSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

/**
 * Maps error codes to categories
 */
export const ErrorCodeCategory: Record<ErrorCode, ErrorCategory> = {
  // Auth errors
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_INVALID_TOKEN]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_EXPIRED_TOKEN]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_REFRESH_TOKEN_REVOKED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.AUTH_MUST_CHANGE_PASSWORD]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_PASSWORD_RESET_REQUIRED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_SESSION_EXPIRED]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_CSRF_TOKEN_MISSING]: ErrorCategory.AUTHENTICATION,
  [ErrorCode.AUTH_CSRF_TOKEN_INVALID]: ErrorCategory.AUTHENTICATION,

  // Tenant errors
  [ErrorCode.TENANT_MISMATCH]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.TENANT_NOT_FOUND]: ErrorCategory.VALIDATION,
  [ErrorCode.TENANT_ACCESS_DENIED]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.TENANT_SUSPENDED]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.ORGANIZATION_NOT_FOUND]: ErrorCategory.VALIDATION,
  [ErrorCode.ORGANIZATION_ACCESS_DENIED]: ErrorCategory.AUTHORIZATION,

  // Validation errors
  [ErrorCode.VALIDATION_FAILED]: ErrorCategory.VALIDATION,
  [ErrorCode.RESOURCE_NOT_FOUND]: ErrorCategory.VALIDATION,
  [ErrorCode.RESOURCE_CONFLICT]: ErrorCategory.VALIDATION,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: ErrorCategory.VALIDATION,
  [ErrorCode.RESOURCE_DELETED]: ErrorCategory.VALIDATION,
  [ErrorCode.INVALID_INPUT]: ErrorCategory.VALIDATION,
  [ErrorCode.MISSING_REQUIRED_FIELD]: ErrorCategory.VALIDATION,
  [ErrorCode.INVALID_EMAIL_FORMAT]: ErrorCategory.VALIDATION,
  [ErrorCode.INVALID_PHONE_FORMAT]: ErrorCategory.VALIDATION,
  [ErrorCode.INVALID_DATE_FORMAT]: ErrorCategory.VALIDATION,
  [ErrorCode.INVALID_CURRENCY_CODE]: ErrorCategory.VALIDATION,

  // Rate limiting
  [ErrorCode.RATE_LIMITED]: ErrorCategory.RATE_LIMITING,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: ErrorCategory.RATE_LIMITING,
  [ErrorCode.TOO_MANY_REQUESTS]: ErrorCategory.RATE_LIMITING,

  // Permission errors
  [ErrorCode.PERMISSION_DENIED]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.ROLE_NOT_FOUND]: ErrorCategory.VALIDATION,
  [ErrorCode.INSUFFICIENT_PRIVILEGES]: ErrorCategory.AUTHORIZATION,
  [ErrorCode.FORBIDDEN_OPERATION]: ErrorCategory.AUTHORIZATION,

  // Database errors
  [ErrorCode.DATABASE_ERROR]: ErrorCategory.DATABASE,
  [ErrorCode.DATABASE_CONNECTION_FAILED]: ErrorCategory.DATABASE,
  [ErrorCode.RLS_POLICY_VIOLATION]: ErrorCategory.DATABASE,
  [ErrorCode.RLS_CONTEXT_MISSING]: ErrorCategory.DATABASE,
  [ErrorCode.TRANSACTION_FAILED]: ErrorCategory.DATABASE,
  [ErrorCode.CONSTRAINT_VIOLATION]: ErrorCategory.DATABASE,
  [ErrorCode.UNIQUE_CONSTRAINT_VIOLATION]: ErrorCategory.DATABASE,
  [ErrorCode.FOREIGN_KEY_VIOLATION]: ErrorCategory.DATABASE,

  // External service errors
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: ErrorCategory.EXTERNAL_SERVICE,
  [ErrorCode.EMAIL_SERVICE_FAILED]: ErrorCategory.EXTERNAL_SERVICE,
  [ErrorCode.STORAGE_SERVICE_FAILED]: ErrorCategory.EXTERNAL_SERVICE,
  [ErrorCode.PAYMENT_SERVICE_FAILED]: ErrorCategory.EXTERNAL_SERVICE,
  [ErrorCode.THIRD_PARTY_API_ERROR]: ErrorCategory.EXTERNAL_SERVICE,

  // System errors
  [ErrorCode.INTERNAL_SERVER_ERROR]: ErrorCategory.SYSTEM,
  [ErrorCode.SERVICE_UNAVAILABLE]: ErrorCategory.SYSTEM,
  [ErrorCode.MAINTENANCE_MODE]: ErrorCategory.SYSTEM,
  [ErrorCode.CONFIGURATION_ERROR]: ErrorCategory.SYSTEM,
  [ErrorCode.FEATURE_DISABLED]: ErrorCategory.SYSTEM,
  [ErrorCode.VERSION_DEPRECATED]: ErrorCategory.SYSTEM,
  [ErrorCode.UPGRADE_REQUIRED]: ErrorCategory.SYSTEM,
};

/**
 * Default HTTP status codes for error codes
 */
export const ErrorCodeHttpStatus: Record<ErrorCode, number> = {
  // Auth errors: 401 Unauthorized
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_EXPIRED_TOKEN]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_REVOKED]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: 403,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 423,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.AUTH_MUST_CHANGE_PASSWORD]: 403,
  [ErrorCode.AUTH_PASSWORD_RESET_REQUIRED]: 403,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCode.AUTH_CSRF_TOKEN_MISSING]: 403,
  [ErrorCode.AUTH_CSRF_TOKEN_INVALID]: 403,

  // Tenant errors: 403 Forbidden
  [ErrorCode.TENANT_MISMATCH]: 403,
  [ErrorCode.TENANT_NOT_FOUND]: 404,
  [ErrorCode.TENANT_ACCESS_DENIED]: 403,
  [ErrorCode.TENANT_SUSPENDED]: 403,
  [ErrorCode.ORGANIZATION_NOT_FOUND]: 404,
  [ErrorCode.ORGANIZATION_ACCESS_DENIED]: 403,

  // Validation errors: 400 Bad Request
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_CONFLICT]: 409,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
  [ErrorCode.RESOURCE_DELETED]: 410,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,
  [ErrorCode.INVALID_EMAIL_FORMAT]: 400,
  [ErrorCode.INVALID_PHONE_FORMAT]: 400,
  [ErrorCode.INVALID_DATE_FORMAT]: 400,
  [ErrorCode.INVALID_CURRENCY_CODE]: 400,

  // Rate limiting: 429 Too Many Requests
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.TOO_MANY_REQUESTS]: 429,

  // Permission errors: 403 Forbidden
  [ErrorCode.PERMISSION_DENIED]: 403,
  [ErrorCode.ROLE_NOT_FOUND]: 404,
  [ErrorCode.INSUFFICIENT_PRIVILEGES]: 403,
  [ErrorCode.FORBIDDEN_OPERATION]: 403,

  // Database errors: 500 Internal Server Error
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.DATABASE_CONNECTION_FAILED]: 503,
  [ErrorCode.RLS_POLICY_VIOLATION]: 403,
  [ErrorCode.RLS_CONTEXT_MISSING]: 500,
  [ErrorCode.TRANSACTION_FAILED]: 500,
  [ErrorCode.CONSTRAINT_VIOLATION]: 400,
  [ErrorCode.UNIQUE_CONSTRAINT_VIOLATION]: 409,
  [ErrorCode.FOREIGN_KEY_VIOLATION]: 400,

  // External service errors: 502 Bad Gateway
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
  [ErrorCode.EMAIL_SERVICE_FAILED]: 502,
  [ErrorCode.STORAGE_SERVICE_FAILED]: 502,
  [ErrorCode.PAYMENT_SERVICE_FAILED]: 502,
  [ErrorCode.THIRD_PARTY_API_ERROR]: 502,

  // System errors: 500 Internal Server Error
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.MAINTENANCE_MODE]: 503,
  [ErrorCode.CONFIGURATION_ERROR]: 500,
  [ErrorCode.FEATURE_DISABLED]: 501,
  [ErrorCode.VERSION_DEPRECATED]: 410,
  [ErrorCode.UPGRADE_REQUIRED]: 426,
};
