#!/bin/bash
# Helper script to migrate tests to new pattern

echo "🔧 Test Migration Helper"
echo "========================"
echo ""
echo "This script helps migrate tests to the new pattern."
echo ""
echo "To migrate a test file:"
echo "1. Copy the file to a temporary location"
echo "2. Remove NestJS TestingModule imports"
echo "3. Add imports from __mocks__, __utils__, __factories__"
echo "4. Replace TestBed with direct instantiation"
echo ""
echo "Example migration commands:"
echo "---------------------------"
echo "# For guard tests:"
echo "cp tests/unit/api/guards/old-test.spec.ts tests/unit/api/guards/old-test.spec.ts.bak"
echo ""
echo "# Then manually update following the pattern in auth.guard.spec.ts"
echo ""
echo "Files to migrate (in order):"
echo "1. guards/ (all guard tests) - Highest priority"
echo "2. services/ (service tests) - Medium priority"
echo "3. controllers/ (controller tests) - Lower priority"