#!/bin/bash

echo "🔐 Testing Token Invalidation After Rotation"
echo "==========================================="

# Cleanup
rm -f *.json *.txt 2>/dev/null

# 1. Login
echo "1. Login..."
curl -c login.txt -X POST http://localhost:3001/api/v1/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@helixcrm.test","password":"Admin123!"}' \
  -o login.json -s

TOKEN1=$(grep refresh_token login.txt | awk '{print $7}')
echo "   Got first refresh token"

# 2. First refresh (rotation)
echo ""
echo "2. First refresh (should rotate)..."
curl -c refresh1.txt -b login.txt -X POST http://localhost:3001/api/v1/auth/refresh \
  -o refresh1.json -s

TOKEN2=$(grep refresh_token refresh1.txt | awk '{print $7}')
echo "   Got second refresh token"

# 3. Verify tokens are different
echo ""
echo "3. Verifying tokens are different..."
if [ "$TOKEN1" = "$TOKEN2" ]; then
    echo "   ❌ FAIL: Tokens are the same!"
    exit 1
else
    echo "   ✅ PASS: Tokens are different"
fi

# 4. Try to use OLD token (should FAIL)
echo ""
echo "4. Testing OLD token invalidation..."
# Create cookie with ONLY the old token
cat > old_cookie.txt << EOF
# Netscape HTTP Cookie File
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/api/v1/auth/refresh	TRUE	0	refresh_token	$TOKEN1
localhost	FALSE	/	TRUE	0	access_token	dummy_value_to_force_error
EOF

OLD_RESPONSE=$(curl -s -b old_cookie.txt -X POST http://localhost:3001/api/v1/auth/refresh)
echo "   Response from old token:"

if echo "$OLD_RESPONSE" | grep -q '"statusCode":401' || \
   echo "$OLD_RESPONSE" | grep -q '"statusCode":403' || \
   echo "$OLD_RESPONSE" | grep -qi "invalid\|unauthorized\|error"; then
    echo "   ✅ SUCCESS: Old token correctly rejected!"
    echo "   Response: ${OLD_RESPONSE:0:150}..."
else
    echo "   ❌ FAILURE: Old token still works!"
    echo "   Full response: $OLD_RESPONSE"
    
    # Decode to see what we got
    echo ""
    echo "   Analyzing response..."
    if echo "$OLD_RESPONSE" | grep -q "access_token"; then
        echo "   ⚠️  Got a NEW access token - security breach!"
    fi
fi

# 5. Try to use NEW token (should WORK)
echo ""
echo "5. Testing NEW token (should work)..."
cat > new_cookie.txt << EOF
# Netscape HTTP Cookie File
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/api/v1/auth/refresh	TRUE	0	refresh_token	$TOKEN2
localhost	FALSE	/	TRUE	0	access_token	dummy_value_to_force_error
EOF

NEW_RESPONSE=$(curl -s -b new_cookie.txt -X POST http://localhost:3001/api/v1/auth/refresh)
if echo "$NEW_RESPONSE" | grep -q "access_token"; then
    echo "   ✅ SUCCESS: New token works!"
else
    echo "   ❌ FAILURE: New token doesn't work"
    echo "   Response: ${NEW_RESPONSE:0:150}..."
fi

# Cleanup
rm -f *.json *.txt 2>/dev/null

echo ""
echo "==========================================="
echo "Test complete. If step 4 shows SUCCESS, the fix is working."