#!/bin/bash

echo "��� Testing Token Invalidation Over HTTPS"
echo "========================================"

# Use HTTPS and ignore SSL errors for testing
CURL_OPTS="-k --cookie-jar cookies.txt --cookie cookies.txt"

# 1. Login
echo "1. Login..."
curl $CURL_OPTS -X POST https://localhost:3001/api/v1/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@helixcrm.test","password":"Admin123!"}' \
  -o response.json -s

echo "   Login completed"

# Extract refresh token from cookie jar
TOKEN1=$(grep -i "refresh_token" cookies.txt | tail -1 | awk '{print $NF}')
echo "   Got first refresh token"

# 2. First refresh
echo ""
echo "2. First refresh..."
curl $CURL_OPTS -X POST https://localhost:3001/api/v1/auth/refresh \
  -o refresh1.json -s

TOKEN2=$(grep -i "refresh_token" cookies.txt | tail -1 | awk '{print $NF}')
echo "   Got second refresh token"

# 3. Verify tokens are different
echo ""
echo "3. Verifying tokens are different..."
if [ "$TOKEN1" = "$TOKEN2" ]; then
    echo "   ❌ FAIL: Tokens are the same!"
    exit 1
else
    echo "   ✅ PASS: Tokens are different"
fi

# 4. Try OLD token (should fail)
echo ""
echo "4. Testing OLD token invalidation..."
# Create a cookie file with ONLY the old token
cat > old_cookies.txt << COOKIE
# HTTP cookie file.
# Generated by curl
localhost	FALSE	/	FALSE	0	refresh_token	$TOKEN1
COOKIE

RESPONSE=$(curl -k -s -b old_cookies.txt -X POST https://localhost:3001/api/v1/auth/refresh)
echo "   Response status check..."

if echo "$RESPONSE" | grep -q '"statusCode":401\|"statusCode":403'; then
    echo "   ✅ SUCCESS: Old token rejected!"
elif echo "$RESPONSE" | grep -qi "unauthorized\|invalid\|error"; then
    echo "   ✅ SUCCESS: Old token rejected!"
else
    echo "   ❌ FAILURE: Old token still works!"
    echo "   Response preview: ${RESPONSE:0:200}"
fi

# 5. Try NEW token (should work)
echo ""
echo "5. Testing NEW token..."
cat > new_cookies.txt << COOKIE
# HTTP cookie file.
# Generated by curl
localhost	FALSE	/	FALSE	0	refresh_token	$TOKEN2
COOKIE

RESPONSE=$(curl -k -s -b new_cookies.txt -X POST https://localhost:3001/api/v1/auth/refresh)
if echo "$RESPONSE" | grep -q "access_token"; then
    echo "   ✅ SUCCESS: New token works!"
else
    echo "   ❌ FAILURE: New token doesn't work"
fi

# Cleanup
rm -f *.json *.txt cookies.txt 2>/dev/null

echo ""
echo "========================================"
echo "Test complete"
